    - sort_values
    - astype('category')
      category แบบมีลำดับ , แบบไม่มีลำดับ
      syn: pandas.Categorical() --> pd.Categorical
           Series.astype('category')
    - การจัดการลำดับ
    - cat 
    - remove_categories()
      syn: df.column.cat.remove_categories(['namecol')
    - add_categories()
      syn: col.cat.add_categories(['namecat.new'])
    - assign value to cat.
      syn: col[0] = 'value in cat.'
    - set_categories() เพื่อกำหนด category ทั้งหมดได้ 
    - reorder_categories() : สามารถเรียงลำดับใหม่ได้
      syn: col.cat.reorder_categories()
    - as_unordered(): ยกเลิกการจัดลำดับโดย

In [1]:
import pandas as pd
import numpy as np

In [3]:
players_df = pd.read_csv('players.csv').loc[:,:'saves']
players_df

,surname,team,position,minutes,shots,passes,tackles,saves
0,Abdoun,Algeria,midfielder,16,0,6,0,0
1,Belhadj,Algeria,defender,270,1,146,8,0
2,Boudebouz,Algeria,midfielder,74,3,28,1,0
3,Bougherra,Algeria,defender,270,1,89,11,0
4,Chaouchi,Algeria,goalkeeper,90,0,17,0,2
...,...,...,...,...,...,...,...,...
590,Holden,USA,midfielder,4,0,2,0,0
591,Howard,USA,goalkeeper,390,0,81,0,14
592,Jozy Altidore,USA,forward,356,8,84,2,0
593,Onyewu,USA,defender,170,1,69,2,0
594,Torres,USA,midfielder,45,1,32,0,0

## สามารถเปลี่ยนให้เป็น category() ได้โดยใช้ pandas.Categorical

In [4]:
# ตอนนี้ col : position เป็น type อะไร : obj = str
players_df.position

0      midfielder
1        defender
2      midfielder
3        defender
4      goalkeeper
          ...
590    midfielder
591    goalkeeper
592       forward
593      defender
594    midfielder
Name: position, Length: 595, dtype: object

### Sort Value
### Unique()

In [5]:
players_df.position.sort_values().unique()

array(['defender', 'forward', 'goalkeeper', 'midfielder'], dtype=object)

## เปลี่ยน column --> categorical

### วิธีที่ 1

In [6]:
players_df.position.astype('category')

0      midfielder
1        defender
2      midfielder
3        defender
4      goalkeeper
          ...
590    midfielder
591    goalkeeper
592       forward
593      defender
594    midfielder
Name: position, Length: 595, dtype: category
Categories (4, object): ['defender', 'forward', 'goalkeeper', 'midfielder']

### วิธีที่ 2

In [7]:
pd.Categorical(players_df.position)

['midfielder', 'defender', 'midfielder', 'defender', 'goalkeeper', ..., 'midfielder', 'goalkeeper', 'forward', 'defender', 'midfielder']
Length: 595
Categories (4, object): ['defender', 'forward', 'goalkeeper', 'midfielder']

### สร้าง col ใหม่ --> add col new in DF

In [8]:
players_df['pos_cat'] = pd.Categorical(players_df.position)
players_df

,surname,team,position,minutes,shots,passes,tackles,saves,pos_cat
0,Abdoun,Algeria,midfielder,16,0,6,0,0,midfielder
1,Belhadj,Algeria,defender,270,1,146,8,0,defender
2,Boudebouz,Algeria,midfielder,74,3,28,1,0,midfielder
3,Bougherra,Algeria,defender,270,1,89,11,0,defender
4,Chaouchi,Algeria,goalkeeper,90,0,17,0,2,goalkeeper
...,...,...,...,...,...,...,...,...,...
590,Holden,USA,midfielder,4,0,2,0,0,midfielder
591,Howard,USA,goalkeeper,390,0,81,0,14,goalkeeper
592,Jozy Altidore,USA,forward,356,8,84,2,0,forward
593,Onyewu,USA,defender,170,1,69,2,0,defender
594,Torres,USA,midfielder,45,1,32,0,0,midfielder

### ลำดับของ Category 
     - ลำดับจากน้อยไปมาก 'ordered = True'

In [9]:
pd.Categorical(players_df.position,ordered=True) #ลำดับแบบ defalt เป็นลำดับตามตัวอักษร

['midfielder', 'defender', 'midfielder', 'defender', 'goalkeeper', ..., 'midfielder', 'goalkeeper', 'forward', 'defender', 'midfielder']
Length: 595
Categories (4, object): ['defender' < 'forward' < 'goalkeeper' < 'midfielder']

In [12]:
pd.Categorical(players_df.position,
               categories =['goalkeeper','defender','midfielder','forward']
               ,ordered=True)

['midfielder', 'defender', 'midfielder', 'defender', 'goalkeeper', ..., 'midfielder', 'goalkeeper', 'forward', 'defender', 'midfielder']
Length: 595
Categories (4, object): ['goalkeeper' < 'defender' < 'midfielder' < 'forward']

In [13]:
players_df['pos_cat'] = pd.Categorical(players_df.position,
               categories =['goalkeeper','defender','midfielder','forward']
               ,ordered=True)
players_df

,surname,team,position,minutes,shots,passes,tackles,saves,pos_cat
0,Abdoun,Algeria,midfielder,16,0,6,0,0,midfielder
1,Belhadj,Algeria,defender,270,1,146,8,0,defender
2,Boudebouz,Algeria,midfielder,74,3,28,1,0,midfielder
3,Bougherra,Algeria,defender,270,1,89,11,0,defender
4,Chaouchi,Algeria,goalkeeper,90,0,17,0,2,goalkeeper
...,...,...,...,...,...,...,...,...,...
590,Holden,USA,midfielder,4,0,2,0,0,midfielder
591,Howard,USA,goalkeeper,390,0,81,0,14,goalkeeper
592,Jozy Altidore,USA,forward,356,8,84,2,0,forward
593,Onyewu,USA,defender,170,1,69,2,0,defender
594,Torres,USA,midfielder,45,1,32,0,0,midfielder

In [14]:
players_df.pos_cat

0      midfielder
1        defender
2      midfielder
3        defender
4      goalkeeper
          ...
590    midfielder
591    goalkeeper
592       forward
593      defender
594    midfielder
Name: pos_cat, Length: 595, dtype: category
Categories (4, object): ['goalkeeper' < 'defender' < 'midfielder' < 'forward']

In [15]:
players_df.sort_values(['team','position']) # sort by string

,surname,team,position,minutes,shots,passes,tackles,saves,pos_cat
1,Belhadj,Algeria,defender,270,1,146,8,0,defender
3,Bougherra,Algeria,defender,270,1,89,11,0,defender
8,Halliche,Algeria,defender,270,2,94,4,0,defender
15,Yahia,Algeria,defender,269,1,79,4,0,defender
5,Djebbour,Algeria,forward,123,3,19,1,0,forward
...,...,...,...,...,...,...,...,...,...
566,Gonzalez,Uruguay,midfielder,63,0,34,2,0,midfielder
567,Lodeiro,Uruguay,midfielder,109,0,37,1,0,midfielder
569,Maxi Pereira,Uruguay,midfielder,570,5,182,15,0,midfielder
571,Perez,Uruguay,midfielder,567,2,252,34,0,midfielder
575,Alvaro Pereira,Uruguay,midfielder,409,6,140,17,0,midfielder

In [19]:
players_df.loc[players_df.team == 'Algeria',:]

,surname,team,position,minutes,shots,passes,tackles,saves,pos_cat
0,Abdoun,Algeria,midfielder,16,0,6,0,0,midfielder
1,Belhadj,Algeria,defender,270,1,146,8,0,defender
2,Boudebouz,Algeria,midfielder,74,3,28,1,0,midfielder
3,Bougherra,Algeria,defender,270,1,89,11,0,defender
4,Chaouchi,Algeria,goalkeeper,90,0,17,0,2,goalkeeper
5,Djebbour,Algeria,forward,123,3,19,1,0,forward
6,Ghezzal,Algeria,forward,40,3,8,0,0,forward
7,Guedioura,Algeria,midfielder,38,0,18,1,0,midfielder
8,Halliche,Algeria,defender,270,2,94,4,0,defender
9,Kadir,Algeria,midfielder,262,0,104,3,0,midfielder
10,Lacen,Algeria,midfielder,270,0,158,8,0,midfielder
11,M'Bolhi,Algeria,goalkeeper,180,0,30,0,12,goalkeeper
12,Matmour,Algeria,midfielder,255,3,68,3,0,midfielder
13,Mesbah,Algeria,midfielder,1,0,1,0,0,midfielder
14,Saifi,Algeria,forward,15,1,3,0,0,forward
15,Yahia,Algeria,defender,269,1,79,4,0,defender
16,Yebda,Algeria,midfielder,269,8,138,10,0,midfielder
17,Ziani,Algeria,midfielder,240,5,93,6,0,midfielder

In [20]:
players_df.loc[players_df.team == 'Algeria',:].sort_values('position')

,surname,team,position,minutes,shots,passes,tackles,saves,pos_cat
8,Halliche,Algeria,defender,270,2,94,4,0,defender
1,Belhadj,Algeria,defender,270,1,146,8,0,defender
15,Yahia,Algeria,defender,269,1,79,4,0,defender
3,Bougherra,Algeria,defender,270,1,89,11,0,defender
5,Djebbour,Algeria,forward,123,3,19,1,0,forward
6,Ghezzal,Algeria,forward,40,3,8,0,0,forward
14,Saifi,Algeria,forward,15,1,3,0,0,forward
4,Chaouchi,Algeria,goalkeeper,90,0,17,0,2,goalkeeper
11,M'Bolhi,Algeria,goalkeeper,180,0,30,0,12,goalkeeper
13,Mesbah,Algeria,midfielder,1,0,1,0,0,midfielder
12,Matmour,Algeria,midfielder,255,3,68,3,0,midfielder
0,Abdoun,Algeria,midfielder,16,0,6,0,0,midfielder
9,Kadir,Algeria,midfielder,262,0,104,3,0,midfielder
16,Yebda,Algeria,midfielder,269,8,138,10,0,midfielder
7,Guedioura,Algeria,midfielder,38,0,18,1,0,midfielder
2,Boudebouz,Algeria,midfielder,74,3,28,1,0,midfielder
10,Lacen,Algeria,midfielder,270,0,158,8,0,midfielder
17,Ziani,Algeria,midfielder,240,5,93,6,0,midfielder

In [21]:
players_df.loc[players_df.team == 'Algeria',:].sort_values('pos_cat') # Sort by Category

,surname,team,position,minutes,shots,passes,tackles,saves,pos_cat
4,Chaouchi,Algeria,goalkeeper,90,0,17,0,2,goalkeeper
11,M'Bolhi,Algeria,goalkeeper,180,0,30,0,12,goalkeeper
8,Halliche,Algeria,defender,270,2,94,4,0,defender
1,Belhadj,Algeria,defender,270,1,146,8,0,defender
15,Yahia,Algeria,defender,269,1,79,4,0,defender
3,Bougherra,Algeria,defender,270,1,89,11,0,defender
13,Mesbah,Algeria,midfielder,1,0,1,0,0,midfielder
12,Matmour,Algeria,midfielder,255,3,68,3,0,midfielder
10,Lacen,Algeria,midfielder,270,0,158,8,0,midfielder
0,Abdoun,Algeria,midfielder,16,0,6,0,0,midfielder
16,Yebda,Algeria,midfielder,269,8,138,10,0,midfielder
7,Guedioura,Algeria,midfielder,38,0,18,1,0,midfielder
2,Boudebouz,Algeria,midfielder,74,3,28,1,0,midfielder
9,Kadir,Algeria,midfielder,262,0,104,3,0,midfielder
17,Ziani,Algeria,midfielder,240,5,93,6,0,midfielder
6,Ghezzal,Algeria,forward,40,3,8,0,0,forward
5,Djebbour,Algeria,forward,123,3,19,1,0,forward
14,Saifi,Algeria,forward,15,1,3,0,0,forward

## การจัดการกับ Category
     - ทำผ่าน submodule cat
     - เรียกดูชื่อหมวดและเปลี่ยนชื่อได้ผ่าน Series.cat.categories
     - add_categories() and remove_categories()

In [23]:
players_df.pos_cat.cat.categories

Index(['goalkeeper', 'defender', 'midfielder', 'forward'], dtype='object')

In [24]:
players_df.pos_cat.cat.categories[0]

'goalkeeper'

In [26]:
players_df.pos_cat.cat.remove_categories('goalkeeper') #ค่าของ cate ที่โดนลบออกไปจากกลายเป็น Nan

0      midfielder
1        defender
2      midfielder
3        defender
4             NaN
          ...
590    midfielder
591           NaN
592       forward
593      defender
594    midfielder
Name: pos_cat, Length: 595, dtype: category
Categories (3, object): ['defender' < 'forward' < 'midfielder']

In [29]:
s_cat = players_df.pos_cat.cat.add_categories('coach')
s_cat

0      midfielder
1        defender
2      midfielder
3        defender
4      goalkeeper
          ...
590    midfielder
591    goalkeeper
592       forward
593      defender
594    midfielder
Name: pos_cat, Length: 595, dtype: category
Categories (5, object): ['goalkeeper' < 'defender' < 'midfielder' < 'forward' < 'coach']

In [31]:
s_cat[0]

'midfielder'

### การ assign ค่านั้นต้องมีอยู่ใน category 
    - เพื่อป้องกันการเขียนผิด หรือ การสะกดผิด

In [33]:
s_cat[0] = 'coach'
s_cat[0]

'coach'

In [34]:
s_cat[0] = 'midfielder'
s_cat[0]

'midfielder'

In [35]:
s_cat.cat.remove_unused_categories() # ลบ category ที่ไม่มีข้อมูลออกไป

0      midfielder
1        defender
2      midfielder
3        defender
4      goalkeeper
          ...
590    midfielder
591    goalkeeper
592       forward
593      defender
594    midfielder
Name: pos_cat, Length: 595, dtype: category
Categories (4, object): ['goalkeeper' < 'defender' < 'midfielder' < 'forward']

## การจัดการกับลำดับ
    - สามารถเรียงลำดับใหม่ได้โดยใช้ method reorder_categories()
    - ยกเลิกการจัดลำดับโดย as_unordered() method

In [37]:
s_cat.cat.as_unordered()

0      midfielder
1        defender
2      midfielder
3        defender
4      goalkeeper
          ...
590    midfielder
591    goalkeeper
592       forward
593      defender
594    midfielder
Name: pos_cat, Length: 595, dtype: category
Categories (5, object): ['goalkeeper', 'defender', 'midfielder', 'forward', 'coach']

In [38]:
s_cat.cat.reorder_categories(['forward','midfielder',
                              'defender','goalkeeper','coach'])

0      midfielder
1        defender
2      midfielder
3        defender
4      goalkeeper
          ...
590    midfielder
591    goalkeeper
592       forward
593      defender
594    midfielder
Name: pos_cat, Length: 595, dtype: category
Categories (5, object): ['forward' < 'midfielder' < 'defender' < 'goalkeeper' < 'coach']